---
- hosts: localhost
  name: Get Adopt OpenJDK JRE / JDK Linux x86_64 install files and sha256 checksums for Hotspot and OpenJ9 JVMs.
  become: no

  tasks:
    - name: Delete previous JRE and JDK files from the download folder.
      file: # https://stackoverflow.com/a/38201526 - will delete the folder and all contents within it
        path: "/tmp/java-download/"
        state: absent

    - name: Recreate downloads directory.
      file: # https://docs.ansible.com/ansible/latest/modules/file_module.html#examples
        path: "/tmp/java-download/"
        state: directory
        mode: 0755

    - name: Download Adopt OpenJDK JRE Linux x86_64 install file for Hotspot JVM.
      get_url: # https://docs.ansible.com/ansible/latest/modules/get_url_module.html
        url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jre_x64_linux_hotspot_8u202b08.tar.gz
        dest: "/tmp/java-download/"
        mode: 0664
        checksum: sha256:b3f9934c6fc83fb2e76a4ded31367e5312013e27d36eac82a6fe1423aae394ce

    - name: Download Adopt OpenJDK JRE Linux x86_64 install file for OpenJ9 JVM.
      get_url: # https://docs.ansible.com/ansible/latest/modules/get_url_module.html
        url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jre_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz
        dest: /tmp/java-download/
        mode: 0664
        checksum: sha256:bcdbbc53e7faaaf8ee480aad21e7396b91daca19f3b1ce1cd9f748437350669b

    - name: Download Adopt OpenJDK JDK Linux x86_64 install file for Hotspot JVM.
      get_url:
        url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz
        dest: "/tmp/java-download/"
        mode: 0664
        checksum: sha256:f5a1c9836beb3ca933ec3b1d39568ecbb68bd7e7ca6a9989a21ff16a74d910ab

    - name: Download Adopt OpenJDK JDK Linux x86_64 install file for OpenJ9 JVM.
      get_url:
         url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz
         dest: "/tmp/java-download/"
         mode: 0664
         checksum: sha256:cdfa82fc46a70f054f2821d7cb2b7c30be2a6c0e0b7c4bbbee357fca1fbee740
