---
- name: Install and configure Mezzanine.
  hosts: all
  become: no
  gather_facts: yes
  roles:
    - role: configure-centos8
    - role: install-postgresql
      vars:
        postgresql_database_name: "{{ common_username }}"
        postgresql_schema_name: "{{ common_username }}"
        postgresql_app_user: "{{ common_username }}"
        postgresql_app_user_password: "{{ common_password }}"
    - role: mezzanine-example
      vars:
        app_username: "{{ common_username }}"
        app_password: "{{ common_password }}"
        # Needed for local_settings.py template.
        postgresql_database_name: "{{ common_username }}"
        postgresql_app_user: "{{ common_username }}"
        postgresql_app_user_password: "{{ common_password }}"


# https://docs.ansible.com/ansible/latest/modules/yum_module.html
# - name: Update the system & reboot.
#   hosts: all
#   become: yes
#   tasks:
#     - name: yum update the cluster.
#       yum:
#         name: '*'
#         state: latest
#     - name: Reboot after update.
#       reboot:
#   # Do one machine at a time so downloads are quicker. - https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#rolling-update-batch-size
#   serial: 1
