all:
  hosts:
    my-centos-8-vm:
    centos-8-01:
    centos-8-02:
    centos-8-03:
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-inventory
  # https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-aliases
  vars:
    ansible_user: vagrant
    ansible_connection: ssh
  children:
    webservers:
      hosts:
        my-centos-8-vm:
        centos-8-01:
        centos-8-02:
        centos-8-03:
