all:
  hosts:
    almalinux-9-vm-01:
    #mezzanine-server:
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-inventory
  # https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-aliases
  vars:
    ansible_user: vagrant
    ansible_connection: ssh
    # https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html#using-python-3-on-the-managed-machines-with-commands-and-playbooks
    #ansible_python_interpreter: /usr/bin/python
  children:
    test:
      hosts:
        almalinux-9-vm-01:
    webservers:
      hosts:
        almalinux-9-vm-01:
        #mezzanine-server:
