all:
  hosts:
    my-centos-8-vm:
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-inventory
  vars:
    ansible_user: vagrant
    ansible_connection: ssh
