---
# https://docs.ansible.com/ansible/latest/modules/django_manage_module.html
# install-pip-packages-into-venv.yml - Create venv, install pip packages, and activate venv.
# clone-mezzanine-base-project - Start Django project. django-admin startproject my-project .
- name: Update Django's local_settings.py file.
  template:
    src: templates/local_settings.py.j2
    dest: "{{ project_path }}/{{ project_name}}/local_settings.py"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

# Create the database - python manage.py migrate
- name: Create the database.
  django_manage: 
    command: "migrate"
    app_path: "{{ project_path }}"
    virtualenv: "{{ venv_project_path }}"
# Run dev server - python manage.py runserver
# Create a django app - python manage.py startapp my-app
# Update app models and the database.

# Create the superuser - python manage.py createsuperuser
- name: Check if super user exists.
  command: echo "from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(username='{{ postgresql_app_user }}').count()>0)" | {{ venv_project_path }}/bin/python ./manage.py shell
  args:
    chdir: "{{ project_path }}"
  register: superuser_existed
  # Don't report it as changed
  changed_when: False

- name: Create the superuser.
  django_manage: 
    command: "createsuperuser --noinput --username={{ postgresql_app_user }} --email={{ postgresql_app_user }}@localhost"
    app_path: "{{ project_path }}"
    virtualenv: "{{ venv_project_path }}"
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html
  environment:
  # https://docs.djangoproject.com/en/3.0/ref/django-admin/#createsuperuser
    DJANGO_SUPERUSER_PASSWORD: "{{ postgresql_app_user_password }}"
  # Run and report changed only if the superuser didn't exist.
  when: not superuser_existed
# https://github.com/ansible/ansible/issues/29786 - Not idempotent yet.


