---
# https://docs.gunicorn.org/en/stable/deploy.html#systemd
- name: Create gunicorn.service systemd file.
  template:
    src: templates/gunicorn.service.j2
    dest: "{{ systemd_admin_service_file_path }}/gunicorn.service"
    mode: '0644'
    owner: root
    group: root
  notify: restart gunicorn

- name: Create gunicorn.socket systemd file.
# https://docs.ansible.com/ansible/latest/modules/template_module.html
  template:
    src: templates/gunicorn.socket.j2
    dest: "{{ systemd_admin_service_file_path }}/gunicorn.socket"
    mode: '0644'
    owner: root
    group: root
  notify: restart gunicorn
