# Double-check that we still have the basics - https://eklitzke.org/lobotomizing-gnome
- name: Ensure core Gnome packages are still installed
  dnf:
    name:
      - eog
      - evince
      - evolution-data-server
      - flatpak
      - gdm
      - gnome-keyring
      - gnome-menus
      - gnome-screenshot
      - gnome-shell
      - gnome-terminal
      - gnome-tweaks
      - nautilus
      - redhat-menus
    state: present # Install packages
