- name: Install Flatpaks
  flatpak:
      name: "{{ item }}"
      state: present
  loop:
    # Messaging & video conferencing
    - org.signal.Signal
    - com.slack.Slack
    - com.microsoft.Teams
    - com.discordapp.Discord
    - us.zoom.Zoom
    # Internet
    - com.dropbox.Client
    - org.mozilla.firefox
    # Development
    - com.getpostman.Postman
