- name: Install 7zip & plugins
  package: # Use system generic package manager, doesn't always work but works with dnf
      name:
        - p7zip.x86_64
        - p7zip-plugins.x86_64
      state: present

- name: Install VIM
  package:
      name: vim
      state: present

- name: Install Anki
  package:
      name: anki
      state: present

- name: Install Clementine
  package:
      name: clementine
      state: present

- name: Install Ansible
  package:
      name: ansible
      state: present

- name: Install htop
  package:
      name: htop
      state: present

- name: Install KeePassXC
  package:
      name: keepassxc
      state: present

- name: Install menulibre - GUI Applications menu editor
  package:
      name: menulibre
      state: present

- name: Install Seahorse - GUI keyring manager
  package:
      name: menulibre
      state: present

- name: Install lm_sensors hardware monitoring
  package:
      name: lm_sensors
      state: present

- name: Install Midnight Commander
  package:
      name: mc
      state: present

- name: Install Shutter
  package:
      name: shutter
      state: present

- name: Install Mozilla Thunderbird
  package:
      name: thunderbird
      state: present

- name: Install VLC Player
  package:
      name: vlc
      state: present

- name: Install Okular
  package:
      name: okular
      state: present

- name: Install Steam
  package:
      name: steam
      state: present

- name: Install qbittorrent
  package:
      name: qbittorrent
      state: present

- name: Install xset (disable mouse accel)
  package:
      name: xset
      state: present

- name: Install Gnome shell extensions
  package:
      name: "{{ item }}"
      state: present
  loop:
    - gnome-extensions-app
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-openweather
    - gnome-shell-extension-workspace-indicator
    - gnome-shell-extension-sound-output-device-chooser
    - gnome-shell-extension-apps-menu
    - gnome-shell-extension-window-list
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-drive-menu
    - gnome-shell-extension-user-theme
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extension-gamemode
    - gnome-shell-extension-freon
    - gnome-shell-extension-drive-menu

- name: Import Visual Studio Code key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code YUM repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Update cache and install Visual Studio Code
  package:
      name: code
      update_cache: yes
      state: present

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Install the 'Multimedia' package group
  yum:
    name: "@Multimedia"
    state: present

- name: Install the 'Sound and video' package group
  yum:
    name: "@Sound-and-video"
    state: present

# https://fedoraproject.org/wiki/Workstation/Third_Party_Software_Repositories#Managing_third_party_repositories_using_DNF
- name: Install Fedora Work Stations
  package:
      name: fedora-workstation-repositories
      state: present

# https://docs.fedoraproject.org/en-US/quick-docs/installing-chromium-or-google-chrome-browsers/
- name: Enable Google Chrome in fedora-workstation-repositories
  command: dnf config-manager --set-enabled google-chrome

- name: Install Google Chrome
  package:
      name: google-chrome-stable
      update_cache: yes
      state: present

- name: Install Flatpak
  package:
      name: flatpak
      state: present

- name: Enable Flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
