- name: Configure Gnome DE.
  import_tasks: set-up-gnome.yml
  become: yes
  when: using_gnome_de

# TODO !!!
- name: Configure XFCE DE.
  import_tasks: set-up-xfce.yml
  become: yes
  when: using_xfce_de

- name: Configure KDE DE.
  import_tasks: set-up-xfce.yml
  become: yes
  when: using_kde_de

- name: Add ~/.bashrc entries
  import_tasks: set-up-bashrc.yml
  become: yes

- name: Add ~/.vimrc entries
  import_tasks: set-up-vimrc.yml
  become: yes

- name: Add ~/.xprofile entries
  import_tasks: set-up-xprofile.yml
  become: yes

# Handled by a new role.
#- name: Install RPM Fusion.
#  import_tasks: install-rpm-fusion.yml
#  become: yes

- name: Install software - dnf.
  import_tasks: install-software-dnf.yml
  become: yes

- name: Install software - flatpak.
  import_tasks: install-software-flatpak.yml
  become: yes
