---
# NOT NEEDED IN CENTOS8
# - name: Add centos-release-scl Package
# # https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql10/
# # https://wiki.centos.org/AdditionalResources/Repositories/SCL
#   package:
#     name:
#       - centos-release-scl
#     state: present

# https://fedoraproject.org/wiki/EPEL & https://wiki.almalinux.org/repos/Extras.html
- name: DNF Config management.
  shell: dnf config-manager --set-enabled crb

- name: Add Fedora EPEL repository.
  package:
    name: epel-release
    state: present
    update_cache: yes
