---
- name: Copy my ssh keys to the VM(s).
  import_tasks: deploy-my-public-ssh-key.yml
  become: false

- name: .bashrc customisations.
  import_tasks: set-up-bashrc.yml
  become: true

- name: Add EPEL repo.
  import_tasks: add-yum-repos.yml
  become: true

# Force update cache here hoping to fix package no found later.
- name: Update Package Cache.
  tags: always
  dnf:
    update_cache: yes
  become: true
  #changed_when: false

- name: Upgrade all packages.
  import_tasks: update-os.yml
  become: true

- name: Install miscellaneous packages.
  import_tasks: install-packages.yml
  become: true

- name: Install miscellaneous package groups.
  import_tasks: install-package-groups.yml
  become: true

- name: Set locale settings.
  import_tasks: set-locale-settings.yml
  become: true

# - name: Install and configure Postfix mail server.
#   import_tasks: set-up-mail-server.yml
#   become: yes
