---
- name: Configure Fedora to my liking.
  hosts: laptop-dell-lan
  become: yes
  gather_facts: yes
  roles:
    # https://galaxy.ansible.com/robertdebock/rpmfusion
    - robertdebock.rpmfusion
    - fedora-post-installation-configuration
