---
- name: Refresh cache and upgrade all packages.
  import_tasks: update-centos.yml
  become: yes

- name: .bashrc customisations.
  import_tasks: set-up-bashrc.yml
  become: yes

- name: My laptop to vagrant VM SSH key.
  import_tasks: deploy-my-public-ssh-key.yml
  become: no

- name: Set locale settings.
  import_tasks: set-locale-settings.yml
  become: yes

- name: Install Python 3.
  import_tasks: install-python3.yml
  become: yes

- name: Install "Development Tools" group.
  import_tasks: install-development-tools-group.yml
  become: yes
