---
- name: .bashrc customisations.
  import_tasks: set-up-bashrc.yml
  become: yes

- name: My laptop to vagrant VM SSH key.
  import_tasks: deploy-my-public-ssh-key.yml

- name: Install Python 3.
  import_tasks: install-python3.yml
  become: yes