---
- name: Add EPEL and SCL repos.
  import_tasks: add-yum-repos.yml
  become: yes

- name: Refresh cache and upgrade all packages.
  import_tasks: update-centos.yml
  become: yes

- name: .bashrc customisations.
  import_tasks: set-up-bashrc.yml
  become: yes

- name: My laptop to vagrant VM SSH key.
  import_tasks: deploy-my-public-ssh-key.yml
  become: no

- name: Set locale settings.
  import_tasks: set-locale-settings.yml
  become: yes

- name: Install and configure Postfix mail server.
  import_tasks: set-up-mail-server.yml
  become: yes

- name: Install miscellaneous packages.
  import_tasks: install-miscellaneous-packages.yml
  become: yes

- name: Install SELinux Management Tools.
  import_tasks: install-selinux-tools.yml
  become: yes

- name: Install Python 3.
  import_tasks: install-python3.yml
  become: yes

- name: Install Java JDK.
  import_tasks: install-java-jdk.yml
  become: yes

- name: Install "@Development Tools" group.
  import_tasks: install-development-tools-group.yml
  become: yes

- name: Install Docker
  import_tasks: install-docker.yml
  become: yes
