---
- name: Save the output of a module task to a variable.
  # https://docs.ansible.com/ansible/latest/modules/command_module.html
  # -un returns the usernmae
  command: id -un
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#registering-variables
  register: login_name
# https://docs.ansible.com/ansible/latest/modules/debug_module.html
- debug:
    msg: "Registered variable - logged in as user {{ login_name.stdout }}"
- name: "The entire variable of login_name"
  debug:
    var: login_name
