---
# TAKEN FROM https://galaxy.ansible.com/geerlingguy/postgresql
# Currently not working as postgres.service isn't being used, we are using pg_ctl instead
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    enabled: yes
    #sleep: 5 # Doesn't exist in CentOS

# - name: start postgresql
#   command: "{{ postgresql_bin_path }}/pg_ctl start -D {{ postgresql_data_dir }} -l {{ postgresql_logfile }}"
#   become: true
#   become_user: "{{ postgresql_user }}"

# - name: restart postgresql
#   command: "{{ postgresql_bin_path }}/pg_ctl restart -D {{ postgresql_data_dir }} -l {{ postgresql_logfile }}"
#   become: true
#   become_user: "{{ postgresql_user }}"

- name: restart nginx
# https://docs.ansible.com/ansible/latest/modules/service_module.html
  service:
    name: nginx
    state: restarted
    enabled: yes