---
- name: restart nginx
# https://docs.ansible.com/ansible/latest/modules/service_module.html
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: true
  become_user: root

- name: restart gunicorn.socket
  systemd:
    name: gunicorn.socket
    state: restarted
    enabled: yes
  become: true
  become_user: "{{ username }}"

- name: restart gunicorn.service
  systemd:
    name: gunicorn.service
    state: restarted
    enabled: yes
  become: true
  become_user: "{{ username }}"