---
- hosts: localhost
  name: Get Hadoop install binary and sha256 checksum.
  become: no

  tasks:
    - name: Delete previous Hadoop files from the download folder.
      file: # https://stackoverflow.com/a/38201526 - will delete the folder and all contents within it
        path: "/tmp/hadoop-download/"
        state: absent

    - name: Recreate Hadoop download directory.
      file: # https://docs.ansible.com/ansible/latest/modules/file_module.html#examples
        path: "/tmp/hadoop-download/"
        state: directory
        mode: 0755

    - name: Download Hadoop Linux install tarball.
      get_url: # https://docs.ansible.com/ansible/latest/modules/get_url_module.html
        url: http://mirror.ventraip.net.au/apache/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz
        dest: "/tmp/hadoop-download/"
        mode: 0664
        checksum: sha256:1c02ccc60a09c63a48dc4234ffd3aed1b75e5a1f2b49d60927eda114b93dd31a
