# https://opensource.com/article/18/7/sysadmin-tasks-ansible
---
- hosts: opendev-centos-vm, my-centos-vm
  name: Upload a public ssh key.
  become: no

  tasks:
    - name: Copy my public ssh key.
      authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.key }}"
        state: "{{ item.state }}"
        comment: "{{ item.comment }}"
      loop:
        - { user: 'vagrant', key: "{{ lookup('file', '/home/dhall/.ssh/id_ed25519_vagrant.pub') }}", state: 'present', comment: 'dhall@unclassified->vagrant-VMs' }
