--- # The beginning of a YAML file
- hosts: localhost,home # Define which host group in my inventory to run the plays of this playbook agaisnt
  name: My Feodra post installation tasks. # Playbook description
  become: yes # Allow privilege escalation, default is sudo.

  tasks: # One or more tasks are about to be defined.
   # Remove unwanted Gnome software - https://eklitzke.org/lobotomizing-gnome
    - name: Remove unwanted Gnome packages # Task description
      dnf: # Specific package manager to use
        name: # Package names
          - cheese # Gnome web camera integration
          - evolution # Gnome mail, contacts, and calendar.
          - evolution-ews
          - evolution-help
          - gfbgraph # GLib/GObject wrapper for the Facebook API - https://wiki.gnome.org/Projects/GFBGraph
          - gnome-boxes # VM
          - gnome-contacts
          - gnome-documents
          - gnome-maps
          - gnome-weather
          - rhythmbox # Gnome music player
          - totem # Gnome video player - https://github.com/GNOME/totem
        state: absent # Uninstall packages
    # Double-check that we still have the basics - https://eklitzke.org/lobotomizing-gnome
    - name: Ensure core Gnome packages are still installed
      dnf:
        name:
          - eog
          - evince
          - evolution-data-server
          - flatpak
          - gdm
          - gnome-keyring
          - gnome-menus
          - gnome-screenshot
          - gnome-shell
          - gnome-terminal
          - gnome-tweaks
          - nautilus
          - redhat-menus
        state: present # Install packages
    # Install software that I use
    - name: Install 7zip & plugins
      package: # Use system generic package manager, doesn't always work but works with dnf
          name:
            - p7zip.x86_64
            - p7zip-plugins.x86_64  
          state: present
    - name: Install Anki
      package:
          name: anki.noarch
          state: present
    - name: Install Clementine
      package:
          name: clementine.x86_64
          state: present
    - name: Install Gnome Commander
      package:
          name: gnome-commander.x86_64
          state: present
    - name: Install htop
      package:
          name: htop.x86_64
          state: present
    - name: Install KeePassXC
      package:
          name: keepassxc.x86_64
          state: present
    - name: Install menulibre - GUI Applications menu editor
      package:
          name: menulibre.noarch
          state: present
    - name: Install Midnight Commander
      package:
          name: mc.x86_64
          state: present
    - name: Install Shutter
      package:
          name: shutter.noarch
          state: present
    - name: Install Mozilla Thunderbird
      package:
          name: thunderbird.x86_64
          state: present
    - name: Install vlc Player
      package:
          name: vlc.x86_64
          state: present
    - name: Install Flatpaks (Atom Text Editor, Dropbox, Spotify)
      flatpak: # Install from flatpak
          name:
            - io.atom.Atom
            - com.dropbox.Client
            - com.spotify.Client
          state: present

